### ISSUE TITLE
No titolo lol

### ISSUE THREAD

**Issue by Nikicoraz** [FedericoSlongo/Simple_GDR#1]
Dovresti fare una release con l'ultima versione del codice
⣿⠛⢻⣿⣿⣿⣿⠛⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ ⣿⠀⠀⠙⢿⣿⣿⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ ⣿⠀⢰⣄⠀⠻⣿⠀⢸⣿⣿⡿⠿⠿⠿⠿⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ ⣿⠀⢸⣿⣦⡀⠈⠀⢸⣿⣿⣷⣤⣤⣤⣤⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ ⣿⠀⢸⣿⣿⣿⣆⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ ⣿⣶⣾⣿⣿⣿⣿⣦⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ ⣿⡟⠻⣿⣿⣿⣿⠟⢻⣿⣿⡿⠿⠿⣿⣿⣿⠟⠛⠿⠿⣿⣿⠁⢀⡈⠉⠙⢿⣿ ⣿⡇⠀⣿⣿⣿⣿⠀⢸⡟⠁⢀⣀⣀⠈⠹⡇⠀⣶⣤⡄⠈⣿⠀⢸⣿⣿⣦⠀⢻ ⣿⡇⠀⠟⢀⠈⢻⠀⢸⠀⠀⣿⣿⣿⠆⠀⡇⠀⠉⠉⢀⣰⣿⠀⢸⣿⣿⡿⠀⣸ ⣿⡇⠀⣠⣾⣷⡀⠀⢸⣦⡀⠈⠉⠉⢀⣰⡇⠀⣷⣤⡀⠙⣿⠀⢸⣿⠿⠁⢠⣿ ⣿⣷⠾⠛⠛⠻⠿⣷⣿⡿⠿⣿⣿⣿⡿⠿⢷⣴⣿⣿⡿⠶⠛⠤⣄⣀⣠⣴⣿⣿ ⣿⣿⠀⢰⣶⣦⠀⢸⡿⠁⠀⢹⣿⡏⢀⣤⣀⣿⣿⡟⠀⣠⣶⣤⣾⣿⣿⣿⣿⣿ ⣿⣿⠀⠘⠋⠁⣠⣾⠃⢠⡇⠀⢻⣧⣀⠉⠙⠛⢿⣧⣀⣀⠉⠙⢿⣿⣿⣿⣿⣿ ⣿⣿⠀⢰⣾⣿⣿⠇⢀⣠⣤⡄⠈⣿⣿⢿⣷⡆⠀⣿⣿⣿⡿⠆⢈⣿⣿⣿⣿⣿ ⣿⣿⣀⣼⣿⣿⣯⣀⣼⣿⣿⣿⣄⣸⣧⣄⣀⣀⣴⣿⡉⣀⣠⣤⣾⣿⣿⣿⣿⣿

**Comment by FedericoSlongo** [comment]
No

**Comment by Nikicoraz** [comment]
:(

**Comment by FedericoSlongo** [comment]
### 

1. > [`**_dududududu_**`](https://github.com/FedericoSlongo/Simple_GDR/issues/1)
